name: Math Utils CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  call-reusable-workflow:
    uses: your-org/reusable-python-ci/.github/workflows/python-ci.yml@main
    with:
      python-version: "3.10"
      requirements-file: "requirements.txt"
